# Generated by Django 6.1.1 on 2026-09-23 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('student', 'Student Boarding'), ('general', 'General Accommodation'), ('both', 'Both')], default='general', max_length=10)),
                ('listing_type', models.CharField(choices=[('room_shared', 'Shared Room'), ('room_single', 'Single Room'), ('cottage', 'Cottage'), ('flat', 'Flat/Apartment'), ('house', 'Full House')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('nearest_institution', models.CharField(blank=True, help_text='e.g. University of Zimbabwe, NUST — only relevant for student category', max_length=150)),
                ('address_detail', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_period', models.CharField(choices=[('per_month', 'Per Month'), ('per_semester', 'Per Semester'), ('per_year', 'Per Year')], default='per_month', max_length=20)),
                ('meals_included', models.BooleanField(default=False)),
                ('gender_specific', models.CharField(choices=[('male', 'Male only'), ('female', 'Female only'), ('mixed', 'Mixed/Any')], default='mixed', max_length=10)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('utilities_included', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('contact_whatsapp', models.CharField(help_text='e.g. 263771234567 (no + or spaces)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
        ),
    ]
