# Generated by Django 6.1.1 on 2026-09-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_latitude_listing_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='occupied_spots',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='How many of those spots are currently taken', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='room_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of people this room fits (only relevant for Shared Room listings)', null=True),
        ),
    ]
